image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
    PYTHON: "C:\\Python38-x64\\python.exe"

install:
  - cmd: >-
      set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts
      "%PYTHON%" -m pip install --user conan
      choco install ninja -y

build_script:
  - cmd: >-
      cmake --preset ninja-multi
      cmake --build --preset ninja-multi-release

test_script:
  - cmd: >-
      cd build
      ctest -C Release

