https://www.geeksforgeeks.org/cin-get-in-c-with-examples/
https://www.geeksforgeeks.org/basic-input-output-c/
https://www.geeksforgeeks.org/endl-vs-n-in-cpp/
https://www.geeksforgeeks.org/problem-with-scanf-when-there-is-fgetsgetsscanf-after-it/
https://www.geeksforgeeks.org/cincout-vs-scanfprintf/
https://www.geeksforgeeks.org/how-to-use-getline-in-c-when-there-are-black-lines-in-input/
https://www.geeksforgeeks.org/difference-between-scanf-and-gets-in-c/
https://www.geeksforgeeks.org/manipulators-in-c-with-examples/
http://www.cplusplus.com/reference/iolibrary/
http://h30266.www3.hpe.com/odl/unix/progtool/deccxx71/6026pro_iostr.html
https://www.geeksforgeeks.org/manipulators-in-c-with-examples/
