#include <iostream>
#include <csignal>
#include <cstdlib>// for  exit()
#include <unistd.h>// getpid()

/*
Signals in computers are a way of communication between the process and the OS. When a running program undergoes some serious error then the OS sends a signal to the process and the process further may not execute. Some processes may have a signal handler which does some important tasks before the process leaves the CPU.

Signal and interrupt are basically same but a small distinction exists i.e interrupts are generated by the processor and handled by the kernel but signals are generated by the kernel and handled by the process. Error signals generally causes termination of the program and a core dump file is created named core, which stores the state of the process at the moment of termination. This file can be investigated using debugger to know the cause of program termination.
 
 
SIGILL:
    This signal denotes illegal instruction. When a garbage instruction or instruction which a program has no privilege to execute, is executed then this signal is generated. C does not produce illegal instruction so there is no chance of facing such error signal, as the probable cause may be that the object file may be corrupted. This signal is also generated when stack overflow occurs.
    

SIGSEGV:
    The signal is generated when process tries to access memory location not allocated to it, like de-referencing a wild pointer which leads to “segmentation fault”.

SIGABRT:
    If an error itself is detected by the program then this signal is generated using call to abort(). This signal is also used by standard library to report an internal error. assert() function in c++ also uses abort() to generate this signal.

SIGFPE: 
    Error that occurred like division by zero, floating point error
    
SIGBUS:
     This signal is also produced when an invalid memory is accessed. It may seem to be same like SIGSEGV but in SIGSEGV, the memory location referenced is valid but in case of SIGBUS, memory referenced does not exist i.e de-referencing a memory location out of memory space.
     
     
SIGSYS:
    This signal is sent to process when an invalid argument is passed to a system call.

SIGTRAP:
    This signal is send to process when an exception is occurred. This is requested by the debugger to get informed. For example, if a variable changes its value then this will trigger it.
    
SIGTERM:
    The SIGTERM signal is a generic signal used to cause program termination. Unlike SIGKILL, this signal can be blocked, handled, and ignored. It is the normal way to politely ask a program to terminate.
    The shell command kill generates SIGTERM by default.


raise() function

csignal header file declared the function raise() to handle a particular signal. Signal learns some unusual behavior in a program, and calls the signal handler. It is implemented to check if the default handler will get called or it will be ignored.

Syntax:

int raise ( int signal_ )
*/



sig_atomic_t s_value = 0; 
void handle(int signum) 
{ 
    s_value = signum;
}

void SIGSEGVhandle(int signum) 
{ 
     std::cout << "oh my god! segmenation fault happened"<< std::endl;
     printf("Process %d got signal %d\n", getpid(), signum);
     
     //kill(getpid(), signum);
    exit(signum);
}


void SIGExample()
{
    //SIGILL,SIGINT,SIGSEGV,SIGTERM,SIGABRT,SIGFPE
    signal(SIGTERM, handle); 
    std::cout << "Before called Signal = " << s_value << std::endl; 
    raise(SIGTERM); 
    std::cout << "After called Signal = " << s_value << std::endl;
}

int main()
{
    //first example
    //SIGExample();
    
    //second example
    signal(SIGSEGV, SIGSEGVhandle);
    //signal(SIGSEGV, SIG_DFL);  // restore default behavior
    int *p;
    *p=10;
}
