name: cpp_tutorial CI and Release

on:
  push:
    branches:
      - "master"
    tags:
      - 'v*.*.*'  # Trigger workflow on version tags (e.g., v1.0.0)
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        name: Checkout the repository

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mycpp_image:latest

      - name: Configure CMake
        run: docker run --rm -v ${{ github.workspace }}:/cpp_tutorials mycpp_image:latest cmake -S /cpp_tutorials -G "Ninja Multi-Config" -B /cpp_tutorials/build

      - name: Build with CMake
        run: docker run --rm -v ${{ github.workspace }}:/cpp_tutorials mycpp_image:latest cmake --build /cpp_tutorials/build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cpp_build_output
          path: /cpp_tutorials/build

  release:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        name: Checkout the repository

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # This will use the pushed tag as the release tag
          release_name: Release ${{ github.ref_name }}  # Name the release after the tag
          body: |
            Release notes for version ${{ github.ref_name }}.
          draft: false
          prerelease: false

      - name: Upload build artifacts to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /cpp_tutorials/build/your_build_artifact
          asset_name: your_build_artifact_name
          asset_content_type: application/octet-stream

